### PR TITLE
Add `bind` to reserved words.

### PR DESCRIPTION
**Pull request by nmec**

### CODE REVIEW

**Comment by spicyj** [comment]
AFAIK there's no restriction on using "bind" as an identifier in ES3:

image

(PDF: http://www.ecma-international.org/publications/files/ECMA-ST-ARCH/ECMA-262,%203rd%20edition,%20December%201999.pdf)

Let me know if I'm misunderstanding.

**Comment by nmec** [comment]
Sadly our old friend IE8 does not fully implement ES3 and throws an error when it comes across bind. I tested this PR against IE 8, 9 & 10 as well as Firefox 40 and Chrome 42 and it worked without issue.

**Comment by nmec** [comment]
Would you reconsider merging this? It would be very helpful for people still having to support IE8.

**Comment by spicyj** [comment]
Yeah, I'll take a look when I get a chance…

**Comment by spicyj** [comment]
Here's what I see:

image

Am I missing something?

**Pull request closed without merging**
